### ISSUE TITLE
aide au plugin

### ISSUE THREAD

**Issue by ghost** [Spikharpax/Avatar-Plugin-eeDomus#10]
Bonjour stephane, j'espere tu vas bien?
s'il te plait un aide pour ton plugin eedomus et un autre plugin, j ai un peux modifier le plugin eedomus, parceque avec ton plugin eeDomus il  y avait plusieurs action pour une seule fonction, donc j ai modifier et creer plusieur fonctions pour chaque action, le plugin fonctionne tres bien avec toute les commandes, le probleme et le suivant
j ai creer un plugin scenariochambre j ai la lampe ne s allume pas
info: scénario From: Salon
info: Intent scenariochambre, Syntax: true
info: Action scenariochambre
info: scenariochambre from: Salon To: Salon
info: voici ton scenario
info: Remote play with callback
info: call(scenariochambre) in 47ms
info: eeDomus command: lampLight From: Salon
error: eeDomus Les valeurs pour realiser l'action sont manquantes.
info: Remote speak with callback
info: call(eeDomus) in 31ms
info: Remote speak with callback
voila le code :
Avatar.call('eeDomus',{client:data.client,command:'lampLight',value:'100'},function(){});

autre probleme , moi je suis debutant  pour le moment je ne connais pas gand chose au cron, j ai le plugin scenariochambre qui ne se lance pas, j'ai un peux compris que j ai pas preciser quel piece
"cron": {
		"scenariochambre":   { 
			"name": "scenariochambre",
			"time": "* 7 * * *"
		}
	}
} 
voila l'erreur:
info: Cron: scenariochambre
info: Reloading: scenariochambre
error: Caught exception: TypeError: Cannot read property 'room' of undefined at setClient (C:/Avatar/resources/core/plugins/scenariochambre/scenariochambre.js:123:21) at Object.exports.cron (C:/Avatar/resources/core/plugins/scenariochambre/scenariochambre.js:3:18) at CronJob.onTick (C:\Avatar\resources\core\manager\cron.js:28:28) at callbackWrapper (C:\Avatar\resources\core\node_modules\cron\lib\cron.js:427:24)
info: Cron: scenariz
info: scenariz cron current room by sensor Salon
voici les liens des 2 plugins:
https://drive.google.com/drive/folders/1q9aSAh3JQDo93ARvO460Puq1N7nrZoow?usp=sharing

https://drive.google.com/drive/folders/1ReYmws1Q_QrmHYWzN2sRgNCZ5LgXo1z1?usp=sharing

merci d'avance pour ton precieux aide, passe un bon weekend

**Comment by Spikharpax** [comment]
Bjr,

L'erreur est dans le message:
**Cannot read property 'room' of undefined at setClient (C:/Avatar/resources/core/plugins/scenariochambre/scenariochambre.js:123:21**

La variable 'room' n'est pas accessible dans la fonction setClient, ligne 123. C'est écrit.
Et si tu lis bien le message d'erreur, c'est écrit **'room' of undefined**, donc sans même regarder, tu dois faire quelque chose comme ca dans ton dev (ligne 123):  **data.room**   et **data** n'est pas définie (room of **undefined**) donc essaye de corriger ca et faire en sorte que ta variable room soit reconnue.

Le plugin Scenario déclenche lui-même ses scénarios avec son propre cron. Il n'y a pas besoin de créer des cron supplémentaires. De plus, il permet de régler vocalement le déclenchement, semaine complète, jour de travail, jours, heure, minute.., Tu as un répertoire "démo" avec des fichiers vocaux pour apprendre les règles à dicter et c'est très bien expliqué aussi dans la page d'info du plugin.
J'ai laissé aussi exprès le plugin SARAH-Scenario sur le github parce qu'il est identique et a aussi une très bonne description que tu peux lire.

Pour info, ce pb est lié au plugin scenario et n'a rien à faire dans le plugin eeDomus, pour la prochaine fois, merci de bien qualifier l'issue.
