### ISSUE TITLE
plugin eedomus

### ISSUE THREAD

**Issue by halimgambit** [Spikharpax/Avatar-Plugin-eeDomus#2]
bonjour stephane j ai les commande allume/eteins les lumieres qui ne fonctionne pas, ca affiche dans la console " l'action eedomus a echouer" , aussi pour changer de couleur la commande passe mais aucun changement de couleur, il y a que la commande lightvariator fonctionne treés bien un aide stp cordialement

info: mets les lumières à 10 % From: Salon
info: IntentEEDomus syntax: true
info: ActionEEDomus action: set
info: eeDomus command: set From: Salon
info: Remote speak with callback
info: call(eeDomus) in 36ms
info: eeDomus periphID: 1433999 value: 10
info: eeDomus periphID: 1434007 value: 10
info: mets les lumières en bleu From: Salon
info: IntentEEDomus syntax: true
info: ActionEEDomus action: set
info: eeDomus command: set From: Salon
info: Remote speak with callback
info: call(eeDomus) in 47ms
info: eeDomus periphID: 1434000 value: 0,0,100,0
info: eeDomus periphID: 1434008 value: 0,0,100,0
info: éteins les lumières From: Salon
info: IntentEEDomus syntax: true
info: ActionEEDomus action: switchLight
info: eeDomus command: switchLight From: Salon
info: call(eeDomus) in 21ms
error: l'action EEDomus a échouée

**Comment by Spikharpax** [comment]
Bonjour Gambit,
Déjà je tiens à t'avertir que si tu supprimes cette demande, je ne te répondrais plus jamais.

Ceci dit,
Je ne crois pas que "0,0,100,0" soit une valeur acceptée par ta box domotique.
Je pense que tu dois envoyer un mauvais ID ou une valeur fausse aussi pour allumer ou éteindre.
La 1ère chose à faire quand tu as un problème est de faire un console.log pour visualiser ce que tu envoies et  corriger éventuellement.

**Comment by halimgambit** [comment]
Stephane je me suis tromper c etait pas sur le bon commentaire du plugin et en plus après j ai trouver l erreur alors je ne voulais pas te déranger, merci pour ton aide

Provenance : Courrier<https://go.microsoft.com/fwlink/?LinkId=550986> pour Windows 10

________________________________
De : A.V.A.T.A.R <notifications@github.com>
Envoyé : Sunday, May 26, 2019 12:52:02 PM
À : Spikharpax/Avatar-Plugin-eeDomus
Cc : halimgambit; Author
Objet : Re: [Spikharpax/Avatar-Plugin-eeDomus] plugin eedomus (#2)


Bonjour Gambit,
Déjà je tiens à t'avertir que si tu supprimes cette demande, je ne te répondrais plus jamais.

Ceci dit,
Je ne crois pas que "0,0,100,0" soit une valeur acceptée par ta box domotique.
Je pense que tu dois envoyer un mauvais ID ou une valeur fausse aussi pour allumer ou éteindre.
La 1ère chose à faire quand tu as un problème est de faire un console.log pour visualiser ce que tu envoies et corriger éventuellement.

**Comment by halimgambit** [comment]
je ne comprend pas comment fonctionne ce github je veux ouvrir les posts mais je ne trouve pas comment
