### ISSUE TITLE
aide au plugin

### ISSUE THREAD

**Issue by halimgambit** [Spikharpax/Avatar-Plugin-eeDomus#4]
bonjour stephane,
un aide stp pour ce plugin franchement j ai tout essayer pour la commande mais ca ne fonctionne toujours pas
 a mon avis la commande c est l etat mais ca ne fonctionne pas
j ai toujour cette erreur : 
info: vérifier la connexion internet From: Salon
info: IntentInternet tokens: true
info: Actioninternet
error: call(internet) Cannot read property 'yellow' of undefined
info: call(internet) in 5ms

fichier js:
exports.action = function(data, callback){

  var tblCommand = {
    internet: function() {internet(data, client)}
};

  info("Internet command:", data.action.command.yellow, "From:", data.client.yellow);
  tblCommand[data.action.command]();
  callback();

  var url = 'http://www.google.fr/';
  console.log(url);
  var request = require('request');
  request({ 'uri' : url }, function (err, response, body) {

  var fs   = require('fs');
  fs.exists('./resources/core/plugins/internet/stat.txt', function (exists) {
  var Statt = fs.createWriteStream('./resources/core/plugins/internet/stat.txt');
  Statt.end();
});

  var etat;
  etat = fs.readFileSync("./resources/core/plugins/internet/stat.txt", "UTF-8");
  console.log("Demande explicite contenu fichier stat.txt = "+etat);

  if (err || response.statusCode != 200) {

  if (etat != "NOK") {
  fs.writeFileSync("./resources/core/plugins/internet/stat.txt", "NOK", "UTF-8");
       return;
}

    Avatar.speak(internet.etat + NOK + "pas de connexion internet", data.client, function (){
      Avatar.Speech.end(data.client);
});
    callback();
}

  else {
  if (etat != "OK") {
  fs.writeFileSync("./resources/core/plugins/internet/stat.txt", "OK", "UTF-8");
       return;
}

    Avatar.speak(internet.etat + OK + "la connexion fonctionne correctement", data.client, function (){
      Avatar.Speech.end(data.client);
});
    callback();
}
});
}

**Comment by Spikharpax** [comment]
Je lis comme tu devrais pouvoir le faire:
error: call(internet) Cannot read property 'yellow' of undefined
'yellow' de quelque chose qui n'existe pas... 'undefined' en anglais... 
qu'est ce qui a 'yellow' dans ton truc ?
=>  info("Internet command:", data.action.command.yellow, "From:", data.client.yellow);
donc... data.action.command n'existe pas.... 
OK ?
Et donc, à ton niveau pour t'en assurer, tu fais un console.log (et F11 pour ouvrir les log...)
console.log('ici', data.action.command);
jsute avant et je relance mon dev pour voir....

Ce que je viens de faire est la base de la base de la base... même plus que ca... ce qu'on apprend la 1ère minute du 1er cours... 
Je te l'ai déjà dis plusieurs fois, tu devrais apprendre à marcher avant d'essayer de courir. Pourquoi tu n'apprends pas ? 
Pourquoi tu n'utilises pas le plugin Studio ?, tu as de quoi créer un plugin et ensuite quand tu ouvres les fichiers js, tu as un menu (clic droit) qui te permet d’insérer toutes les commandes Avatar...  ET SANS ERREUR.

Pardon mais ce plugin n'est pas un plugin eedomus.
De pus il ne sert à rien du tout.
Si tu n'as pas de connexion internet, Avatar ne fonctionne pas. Tu ne pourras jamais l'exécuter, ni même avoir de réponses...
