### ISSUE TITLE
aide

### ISSUE THREAD

**Issue by halimgambit** [Spikharpax/Avatar-Plugin-eeDomus#7]
bonjour stephane,
 un aide au plugin stp, c est bon j ai appris un peu
je n ai pas de retour vocal au plugin internet

fichier.js
var Promise = require('q').Promise;

require('colors');

exports.action = function(data, callback){

  let client = setClient(data);

  info("internet from:", data.client);
  internet (data, client);
  
  callback();
 
}

function internet (data, client) {

var url = 'http://www.google.fr/';
function http_request (url) {
return new Promise(function (resolve, reject) {
var request = require('request');
request({ 'uri' : url}, function (err, response, body) {
    
  if (err || response.statusCode != 200) {
    return reject ('Désolé je n\'arrive pas accédé a l internet');
}
    resolve(body);
  });
    
  });
} 

  var fs   = require('fs');
  fs.exists('./resources/core/plugins/internet/stat.txt', function (exists) {
  var Statt = fs.createWriteStream('./resources/core/plugins/internet/stat.txt');
  Statt.end();

  });

  var etat;
  etat = fs.readFileSync("./resources/core/plugins/internet/stat.txt", "UTF-8");
  console.log("Demande explicite contenu fichier stat.txt = "+etat);

  if (etat != "NOK") {
  fs.writeFileSync("./resources/core/plugins/internet/stat.txt", "NOK", "UTF-8");
     return;
   } else {
      Avatar.speak(Config.modules.internet.etat+"pas de connexion internet:", data.client, function (){
      Avatar.Speech.end(data.client);
  });
    return callback();
}

  if (etat != "OK") {
  fs.writeFileSync("./resources/core/plugins/internet/stat.txt", "OK", "UTF-8");
      return;
} else {
      Avatar.speak(Config.modules.internet.etat+"la connexion fonctionne correctement:", data.client, function (){
      Avatar.Speech.end(data.client);
  });
    return callback();
}
}

function setClient (data) {

  var client = data.client;
  
  if (data.action.room)
    client = (data.action.room != 'current') ? data.action.room : (Avatar.currentRoom) ? Avatar.currentRoom : Config.default.client;

  if (data.action.setRoom)
    client = data.action.setRoom;

      return client;
}
Cordialement

**Comment by Spikharpax** [comment]
je te l'ai déjà dit, ton plug-in ne sert à rien.
Comment veux-tu dialoguer avec Avatar si tu n'as plus de réseau ? Ca ne pourra évidement pas fonctionner, donc passe à autre chose. Ce truc que tu essayes de porter est à mettre à la poubelle.
Pourquoi tu ne développes pas sur des plug-ins existants et sur ce que tu as ? tu as une box eedomus et j'imagine qu'il y a plein de choses que tu pourrais faire...

Sinon, je suis désolé, Halim mais je ne peux pas développer tes plug-ins. Je pourrais t'aider sur des choses qui nécessitent mon expertise et avec quelqu'un qui a un minimum de compétences pour comprendre ce que je lui explique mais pas pour t'apprendre à développer. Çà sort de mes attributions. Je t'ai donné des sites où tu peux apprendre.

Je te l'ai déjà dit aussi Halim, ne post pas sur des projets qui n'ont rien à voir avec eux.
